### ISSUE TITLE
question about SSL pretraining

### ISSUE THREAD

**Issue by Na-Z** [charusharma1991/SSL_PointClouds#3]
Hi Charu, 

Nice work! 
May I know if the self-supervised pre-training is individually done for each downstream task (i.e., classification, part segmentation, and semantic segmentation) on the corresponding dataset? For example, when you do semantic segmentation on S3DIS, the mode is pre-trained on S3DIS via SSL? If so, how did you form cover tree for scene-level examples in S3DIS?

Thanks,
Na

**Comment by charusharma1991** [comment]
Thanks! Yes, the SSL pre-training is done for each task and each dataset. For semantic segmentation, the SSL network is trained on S3DIS in FSL setup. For that, existing methods mention that each room is split into blocks of area 1m×1m containing 4096 sampled points and each point is represented by a 9D vector. We use the same blocks for rooms with 4096 points in each block and used only 3D points to construct a cover tree for these blocks. Hope that helps!

**Comment by Na-Z** [comment]
Got it. Thanks.

When you do few-shot segmentation on S3DIS, you select mK' point clouds as a support set. May I know the associated annotation of each point cloud in the support set is point-wise labelling or binary labelling in terms of the corresponding class?

**Comment by charusharma1991** [comment]
In segmentation, point-wise labeling is needed but while making a support set, you can pick m samples from each of the K' classes which are 6 areas in this dataset. Our experiment followed the standard setting for S3DIS i.e. we train on samples from 5 areas and test on the one which was left.
