### ISSUE TITLE
Quick convergence of SSL Network

### ISSUE THREAD

**Issue by derektrc** [charusharma1991/SSL_PointClouds#4]
Hello, is the FSL feature extracting network supposed to converge quickly? 

I have run the 3 lines with the provided instructions and default parameters (python test_covertree.py 2.0, python train_FSL.py
, then python train_classifier.py).

Namespace(batch_size=8, dataset_name='../Sydney10', dropout=0.5, emb_dims=1024, epochs=250, exp_name='Sydney10_FSL', k=20, lr=0.001, model='dgcnn', model_path='../SSL/cls_Sydney10/model_3.pth', momentum=0.9, no=1, no_cuda=False, num_points=100, seed=1, split_path='data_sydney10/train_1020_test_1020_1', test_K_way=10, test_N_shots=20, test_batch_size=8, train_K_way=10, train_N_shots=20, use_sgd=False)

Running the classification code with FSL checkpoints model_3.pth vs. model_199.pth seem to produce very similar classification accuracy results.

model_3     -> .805
model_199 -> .830

![pc_acc](https://user-images.githubusercontent.com/5672743/103260868-172f7a00-4954-11eb-9d72-d13a4094ebe6.png)

Is this expected? Thank you!

**Comment by charusharma1991** [comment]
Hi, SSL-FSL network can give spikes in the initial epochs but it won't generalize well that quickly. We have observed generalized results mostly from epochs close to 200 or more.
Thanks!
