### ISSUE TITLE
FileNotFoundError while running train_FSL.py

### ISSUE THREAD

**Issue by Rishab9991** [charusharma1991/SSL_PointClouds#7]
Hello,
I found your code very interesting and wanted to understand it. So, I started to implement your code locally on my system but I came across this error which is shown in the screenshot that is attached below. Kindly help me in resolving this error.

Thanks in advance

![Screenshot (1271)](https://user-images.githubusercontent.com/26292426/112352867-2b83d880-8cf1-11eb-9b86-9e31f402b4bd.png)

**Comment by charusharma1991** [comment]
Hey, you need to create folder name cls_Sydney10 (provided in args list) first as this one is the default path set in args or you can edit that part as per your requirement.
