### ISSUE TITLE
Testing on PointNet and DGCNN separately

### ISSUE THREAD

**Issue by Rishab9991** [charusharma1991/SSL_PointClouds#8]
Hi,
I wanted to know if there is a possibility of testing on PointNet and DGCNN classifiers independently in a FSL setting before applying your self-supervised pre-trained methods to compare the improvement in the accuracy before and after applying the self-supervised pre-trained methods in your implementation which you have done in your paper.

Thank you

**Comment by charusharma1991** [comment]
Yes, it is possible. Make a FSL setup in PointNet and DGCNN code before running.
